spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: edge-service
            client-secret: bookshop-keycloak-secret
            scope: openid,roles
        provider:
          keycloak:
            issuer-uri: http://host.docker.internal:8080/realms/bookshop
